// lib/api/stations.ts

import { readFileSync } from "fs";
import { join } from "path";

// Types
export type Station = {
  id: string;
  nameKanji: string; // e.g. "新宿"
  nameRomaji: string; // e.g. "shinjuku-station"
  prefecture: string; // e.g. "tokyo"
  city: string; // e.g. "shinjuku-ku"
  slug: string; // same as nameRomaji, unique
};

export type Clinic = {
  id: string;
  name: string;
  slug: string;
  address: string;
  station: string; // station nameKanji for display
  stationSlug?: string; // Add this
  specialties: string[];
  phone?: string | null;
  prefecture: string;
  city: string;
  walkingMinutes?: number; // distance from the station
  onlineConsultation?: boolean;
  badge?: string[];
};

// Load generated clinic data (generated by scripts/fetchClinics.ts)
function loadClinics(): Clinic[] {
  try {
    const filePath = join(process.cwd(), "public", "data", "clinics.json");
    const raw = readFileSync(filePath, "utf-8");
    return JSON.parse(raw) as Clinic[];
  } catch (e) {
    console.warn("Clinics JSON not found, falling back to empty list");
    return [];
  }
}

// Load stations from the same JSON (derive unique stations)
function loadStations(): Station[] {
  const clinics = loadClinics();
  const map = new Map<string, Station>();
  clinics.forEach((c) => {
    const key = c.station;
    if (!map.has(key)) {
      // Use provided stationSlug or fallback to generating one
      const slug = c.stationSlug || c.station.replace(/\s+/g, "-").toLowerCase() + "-station";
      map.set(key, {
        id: slug,
        nameKanji: c.station,
        nameRomaji: slug,
        prefecture: c.prefecture,
        city: c.city,
        slug,
      });
    }
  });
  return Array.from(map.values());
}

const stationsCache = loadStations();
const clinicsCache = loadClinics();

/** Get a station by its slug (e.g. "shinjuku-station") */
export async function getStationBySlug(slug: string): Promise<Station | null> {
  const station = stationsCache.find((s) => s.slug === slug);
  return station ?? null;
}

/** Get clinics that belong to a station (by station id) */
export async function getClinicsByStation(
  stationId: string,
  filters?: { specialty?: string; maxWalkingMinutes?: number }
): Promise<Clinic[]> {
  let clinics = clinicsCache.filter((c) => {
    const station = stationsCache.find((s) => s.id === stationId);
    return station && c.station === station.nameKanji;
  });

  if (filters?.specialty) {
    clinics = clinics.filter((c) => c.specialties.includes(filters.specialty!));
  }
  if (filters?.maxWalkingMinutes !== undefined) {
    clinics = clinics.filter(
      (c) => (c.walkingMinutes ?? 999) <= filters.maxWalkingMinutes!
    );
  }
  clinics.sort((a, b) => (a.walkingMinutes ?? 0) - (b.walkingMinutes ?? 0));
  return clinics;
}

/** Helper to generate static params for all stations */
export async function getAllStationSlugs(): Promise<
  { prefecture: string; city: string; stationSlug: string }[]
> {
  return stationsCache.map((s) => ({
    prefecture: s.prefecture,
    city: s.city,
    stationSlug: s.slug,
  }));
}
